<!DOCTYPE html>
<html>
<head>
  <title>Perfy</title>
  <script type="text/javascript" src="/perfy/perfy.js"></script>
  <script type="text/javascript" src="/sample_js/simple.js"></script>
  <script type="text/javascript" src="/sample_js/jquery.js"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      console.log('hello');
    });
  </script>
  <link rel="stylesheet" type="text/css" href="">
</head>
<body>

</body>
</html>
